application: swiki-sixthio
version: 3
runtime: go
api_version: go1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.icos

- url: /.*
  script: _go_app

- url: /res
  static_dir: res

- url: /lib
  static_dir: vendor